### Get all Courses
GET http://localhost:3000/

###
GET http://localhost:3000/users
###
GET http://localhost:3000/users/1

###
GET http://localhost:3000/categories

### Get Course
GET http://localhost:3000/course/1

### get user payment
GET http://localhost:3000/payment/1

